# general settings
name: NAFNet_CLIP_NTIRE2025_1e-4
model_type: SRModel
scale: 1
num_gpu: 1
manual_seed: 728

# dataset and data loader settings
datasets:
  train:
    name: NTIRE2025
    type: PairedImageDataset
    dataroot_gt: datasets/NTIRE2025/AllClear
    dataroot_lq: datasets/NTIRE2025/AllDrop
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: false

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 10
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: test
    type: PairedImageDataset
    dataroot_gt: datasets/NTIRE2025/TEST/GT
    dataroot_lq: datasets/NTIRE2025/TEST/DROP
    io_backend:
      type: disk

# network structures
# network_g:
#   type: NAFNet_3Stage_detail
  # img_channel: 3
  # width: 32
  # middle_blk_num: 12
  # enc_blk_nums: [2, 2, 4, 8]
  # dec_blk_nums: [2, 2, 2, 2]
# network_g:
  # type: PromptIR
  # decoder: true
network_g:
  type: NAFNet_CLIP_2Stage
  # type: Restormer
  # inp_channels: 3
  # out_channels: 3
  # dim: 48
  # num_blocks: [4,6,6,8]
  # num_refinement_blocks: 4
  # heads: [1,2,4,8]
  # ffn_expansion_factor: 2.66
  # bias: False
  # LayerNorm_type: WithBias
  # dual_pixel_task: False

# path
path:
  pretrain_network_g: experiments/NAFNet_CLIP_NTIRE2025/models/net_g_330000.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  # ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000, 600000, 800000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # ssim_opt:
  #   type: log_SSIM_loss
  #   loss_weight: 1.0
  # perceptual_opt:
  #   type: PerceptualLoss
  #   layer_weights:
  #     # before relu
  #     'conv1_2': 0.1
  #     'conv2_2': 0.1
  #     'conv3_4': 1
  #     'conv4_4': 1
  #     'conv5_4': 1
  #   vgg_type: vgg19
  #   use_input_norm: true
  #   perceptual_weight: !!float 0.01
  #   style_weight: 0
  #   range_norm: false
  #   criterion: l1

# validation settings
val:
  val_freq: !!float 10000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 0
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
